name: Build

on:
  push:
    branches-ignore:
      - master

jobs:
  python:
    name: Python ${{ matrix.python }} on ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, ubuntu-latest]
        python: ["3.10", "3.11", "3.12", "3.13", "3.14"]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v7

      - uses: astral-sh/setup-uv@v10
        with:
          python-version: ${{ matrix.python }}

      - run: uv sync

      - run: uv build
