name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version number
        required: true

jobs:
  pip:
    name: Publish package to PyPI

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: astral-sh/setup-uv@v10.2.0

      - run: uv version ${{ github.event.inputs.version }}

      - run: uv build

      - run: uv publish
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}

  release:
    name: Create the release

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Create release
        uses: softprops/action-gh-release@v3
        with:
          draft: false
          prerelease: false
          name: ${{ github.event.inputs.version }}
          tag_name: ${{ github.event.inputs.version }}
