name: Test

on:
  push:
    branches-ignore:
      - master

jobs:
  integration:
    name: Integration (Python ${{ matrix.python }})

    strategy:
      fail-fast: true
      matrix:
        python: ["3.11", "3.12", "3.13", "3.14"]

    runs-on: ubuntu-latest

    services:
      gopos:
        image: ghcr.io/thepieterdc/gopos:latest
        ports:
          - 8000:8000

    steps:
      - uses: actions/checkout@v7

      - uses: astral-sh/setup-uv@v10.2.0
        with:
          python-version: ${{ matrix.python }}

      - run: uv sync

      - name: Wait for gopos
        run: curl --retry 30 --retry-delay 1 --retry-connrefused --retry-all-errors --fail --silent http://localhost:8000/health

      - run: uv run pytest -v ./tests/
