name: Test

on:
  push:
    branches-ignore:
      - master

jobs:
  integration:
    name: Integration (Python ${{ matrix.python }})

    strategy:
      fail-fast: true
      matrix:
        python: ["3.10", "3.11", "3.12", "3.13", "3.14"]

    runs-on: ubuntu-latest

    services:
      gopos:
        image: ghcr.io/thepieterdc/gopos:latest
        ports:
          - 8000:8000

    steps:
      - uses: actions/checkout@v7

      - uses: astral-sh/setup-uv@v10
        with:
          python-version: ${{ matrix.python }}

      - run: uv sync

      - run: uv run pytest -v ./tests/
